# Generated by Django 5.0.6 on 2024-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/categories')),
                ('status', models.IntegerField(default='1')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
