# Generated by Django 5.0.6 on 2024-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='system_setting',
            name='slogan',
            field=models.CharField(default='Shop. Save. Smile.', max_length=250),
        ),
    ]
