# Generated by Django 5.0.6 on 2024-07-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_products_discount_system_setting_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
