# Generated by Django 5.0.6 on 2024-06-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DoB',
            field=models.DateField(blank=True),
        ),
    ]
